clear; close all; clc;fclose('all'); 
hostdir ='F:\aboil\';%C:\my_document\ABOIL\FPGA\matlab_sdoct_pocess\';    % location -> Sample bin file
MZIhostdir ='C:\aboil\MATLAB_SDOCT\MATLAB_SDOCT\'; %'C:\my_document\ABOIL\FPGA\matlab_sdoct_pocess\';    % location -> Calibration bin file
pgmflag = 0;    % flag for saving cx OCT image
flag4refocus = 0;       
destFileName = '';
binBase = dir([hostdir, destFileName, 'raw_3D_camp.bin']);    % file name  -> Sample bin file
MZIbinBase = dir([MZIhostdir destFileName '\xxxxxxxxxxxx.bin']);    % file name -> Calibration bin file

Samplepoints=2048;    % # of points per A-scan -> Sample bin file
LinesperFrame=1000;    % # of A-scan per B-scan -> Sample bin file
Frame_number=500;    % # of B-scan per C-scan -> Sample bin file
y_bg = zeros(Samplepoints, LinesperFrame);    % pre-allocated memory space for each frame -> Sample bin file


MZISamplepoints = 2048;    % # of points per A-scan -> Calibration bin file
MZILinesperFrame = 2;    % # of A-scan per B-scan -> Calibration bin file
MZIRawFringe_init=zeros(MZISamplepoints, MZILinesperFrame);    % pre-allocated memory space for each frame -> Calibration bin file








%% data processed by OCT Core %%
% filename2="C:\my_document\ABOIL\FPGA\OCT_Core\PS_USB_MEMS_Control\Bulkloop\Raw_data_2024_06_07_17_35_59.bin";%Raw_data_2024_05_01_18_52_51_dc_log.bin";
%filename2="F:\aboil\Raw_data_2024_05_01_18_34_27_dc_log.bin";
filename2="F:\aboil\raw_3D_camp.bin";
fid2 = fopen(filename2,'r');
input2 = single((fread(fid2,'single')));
fclose(fid2);

Pixel = 1024;
Line = 1000; %1024;
Frame = length(input2)/1024/Line
ThreeD = single(reshape(input2,[Pixel Line Frame]));

frame1 = ThreeD(:,:,1);

noise = mean(mean(frame1(end/2:end, :)));

denoise_v = abs(frame1-noise); %% v stands for verilog

max_pixel = max(max(denoise_v));

rescale_vdata = denoise_v/max_pixel*65535 ;

figure; imagesc(rescale_vdata);colormap gray;
% imwrite(     uint16( rescale_vdata   ), 'Leo_finger_fpga.pgm', 'pgm');


%% read data generated by vivado to check if the simulation result is ok %%

text = fileread("F:\PS_With_MEMS_5kHz_oct_sys_dc_log_wppff.xpr\PS_With_MEMS_5kHz_oct_sys_dc_log_wppff.xpr\project_1\coe_txt\interp_data_result.txt");
hdata = textscan(text, "%x");
hdata_uint32 = uint32(hdata{1});
float_data = typecast(hdata_uint32, "single");

%% matlab raw data image processing preparing %%




fid = fopen("C:\aboil\MATLAB_SDOCT\MATLAB_SDOCT\k_calibration_OPXION.hex",'r'); %% calibration file
phase_diff = fread(fid,[MZISamplepoints, MZILinesperFrame],'double'); 

phase_diff = single(phase_diff);

figure
plot(phase_diff);

fclose(fid);




cropped_num = 2048;    % cropping data size: from head of each raw-A-line to cropped_num

binBase_Size = size(binBase);

for i = 1:binBase_Size(1)
    filename = [hostdir destFileName binBase(i).name];   
    disp(['Checking file: ', filename]);
% disp(['File exists? ', num2str(exist(filename, 'file'))]);
    fid = fopen(filename,'r');    % open sample bin file
    if fid == -1
        error('could not open file');
    end
    if pgmflag == 1
        mkdir([filename(1:strfind(filename,'_S_')-1) '_log']);    % create the file to save log OCT image
        mkdir([filename(1:strfind(filename,'_S_')-1)]);    % create the file to save linear OCT image
    end 

    Processeddata = zeros(Samplepoints/2,LinesperFrame,Frame_number, 'single');    % pre-allocated memory space for processed OCT data
    Cali_rawdata = zeros(Samplepoints/2,LinesperFrame,Frame_number, 'single');    % pre-allocated memory space for unprocessed OCT data
    Processed = zeros(Samplepoints/2,LinesperFrame,Frame_number, 'single');
    
    

    fid_bg=fopen("F:\aboil\Raw_data_2023_09_05_20_28_33_bg.bin", 'r'); %% background file

    bg = single(fread(fid_bg,[Samplepoints, LinesperFrame],'uint16'));


%     all_fix_rawfringe = uint16(fread(fid,[Samplepoints, LinesperFrame*20],'uint16'));

    original_frame = 20;
    target_frame = 500;
    
    % 原始讀入的 fringe
    all_fix_rawfringe_raw = uint16(fread(fid, [Samplepoints, LinesperFrame * original_frame], 'uint16'));
    
    % 重複
    repeat_times = ceil(target_frame / original_frame);
    all_fix_rawfringe_tmp = repmat(all_fix_rawfringe_raw, 1, repeat_times);
    
    % 截取到正確數量（防止超出）
    all_fix_rawfringe = all_fix_rawfringe_tmp(:, 1 : LinesperFrame * target_frame);


%     fix_bg = uint16(fread(fid_bg,[Samplepoints, LinesperFrame],'uint16'));
    fix_bg_raw = uint16(fread(fid_bg,[Samplepoints, LinesperFrame],'uint16'));
    fix_bg = repmat(fix_bg_raw(:,1), 1, LinesperFrame);     
    for line_index=2:1000
        fix_bg(:, line_index) = fix_bg(:, 1); 
    end



    %% start image processing %%
    tic
% 
%     total_cols = size(all_fix_rawfringe, 2);
%     lines_per_frame = 1000;
%     total_frames = floor(total_cols / lines_per_frame);  % 不足一個 frame 的部分直接忽略

    for framenum = 1:Frame_number%total_frames %
       
        fix_rawfringe = all_fix_rawfringe(:, (framenum*1000-999):(framenum*1000)); %% process 1 frame per iteration
%         fix_rawfringe = all_fix_rawfringe(:, (framenum-1)*lines_per_frame + 1 : framenum*lines_per_frame);

        y_bg = single(fix_rawfringe - fix_bg);
        

        tmpk_fringe = zeros(Samplepoints, LinesperFrame, 'single');
        cali_k_fringe = zeros(Samplepoints, LinesperFrame, 'single');
        k_fringe = zeros(Samplepoints, LinesperFrame, 'single');


        Hamwin = single(hamming(Samplepoints));    % Create the hamming window for spectral shaping
        %equal_space_k = single(  min(phase_diff):((max(phase_diff)-min(phase_diff))/(length(phase_diff)-1)):max(phase_diff)  );    % calibration index for processing
        equal_space_k = single(linspace(0, 1, 2048));
        
       
       

        for cnt=1:1000
            
            tmpk_fringe(:, cnt) = cubic_spline_single(cnt, equal_space_k, y_bg(:, cnt),phase_diff'); %% interpolation

        end



        cali_k_fringe = (tmpk_fringe).*Hamwin;    % spectral shaping
        
        k_fringe = (fft(cali_k_fringe));    % FFT process

    


        Processeddata(1:Samplepoints/2,:,framenum) = k_fringe(1:Samplepoints/2,:);    % processed data
        

    end
    toc 
    fclose('all');    % close the file -> Sample bin file
          
    % figure; imagesc(log10(abs(Processeddata(:,:,12  ))));colormap gray;
    %% export testpattern %%



    filename0="F:\PS_With_MEMS_5kHz_oct_sys_dc_log_wppff.xpr\PS_With_MEMS_5kHz_oct_sys_dc_log_wppff.xpr\project_1\coe_txt\dc_real.txt";
    fd0 = fopen(filename0,'w'); 
    fprintf(fd0,'memory_initialization_radix=16;\n');
    fprintf(fd0,'memory_initialization_vector=\n');
    for k=1:2048
        if(k~=2048)
            fprintf(fd0,'%04x,\n', typecast(Hamwin(k), 'uint32') );
        else
            fprintf(fd0,'%04x;', typecast(Hamwin(k), 'uint32') );

        end
    end

    filename3="F:\PS_With_MEMS_5kHz_oct_sys_dc_log_wppff.xpr\PS_With_MEMS_5kHz_oct_sys_dc_log_wppff.xpr\project_1\coe_txt\dc_imag.txt";
    fd3 = fopen(filename3,'w'); 
    fprintf(fd3,'memory_initialization_radix=16;\n');
    fprintf(fd3,'memory_initialization_vector=\n');
    for k=1:2048
        if(k~=2048)
            fprintf(fd3,'%04x,\n', single(0) );
        else
            fprintf(fd3,'%04x;', single(0) );

        end
    end



    filename1="F:\PS_With_MEMS_5kHz_oct_sys_dc_log_wppff.xpr\PS_With_MEMS_5kHz_oct_sys_dc_log_wppff.xpr\project_1\coe_txt\fix_bg.txt";
    fd1 = fopen(filename1,'w'); 
    fprintf(fd1,'memory_initialization_radix=16;\n');
    fprintf(fd1,'memory_initialization_vector=\n');
    for k=1:2048
        if(k~=2048)
            fprintf(fd1,'%04x,\n', fix_bg(k, 1) );
        else
            fprintf(fd1,'%04x;', fix_bg(k, 1) );

        end
    end


    filename2="F:\PS_With_MEMS_5kHz_oct_sys_dc_log_wppff.xpr\PS_With_MEMS_5kHz_oct_sys_dc_log_wppff.xpr\project_1\coe_txt\fix_rawfringe.txt";
    fd2 = fopen(filename2,'w'); 

    for k=1:2048

            fprintf(fd2,'%04x\n', typecast(fix_rawfringe(k, 1), 'uint16') );

    end

%% vivado silmulation result vs matlab prcessing result (for cubic spline interpolation) %%
    verilog_err = (float_data-tmpk_fringe(:, 1)) ./ tmpk_fringe(:, 1);
    vlogmax = max(verilog_err);
    figure
    plot(verilog_err, 'LineWidth', 3);
    ylim([-1, 1]);

%% save data to pgm %%
    log_data = log10(abs(Processeddata(:,:,1)));
    max_pixel = max(max(log_data));
    rescale_data = log_data/max_pixel*65536 ;
    imwrite(     uint16(  rescale_data   ), 'Leo_finger1.pgm', 'pgm');

%% save processed data to .bin %%       //2025 06 26    //Dan_nigger
    filename_Dnigger = fopen('F:\aboil\raw_3D_camp_processed.bin', 'wb');
    for i = 1 : 120%Frame_number
    log_data_Dnigger = log10(abs(Processeddata(:,:,i)));
    max_pixel_Dnigger = max(max(log_data_Dnigger));
    rescale_data_Dnigger = log_data_Dnigger/max_pixel_Dnigger*65536 ;
    fwrite(filename_Dnigger, rescale_data_Dnigger, 'single');
    end
    
    
    fclose(filename_Dnigger);
    disp('*************************************************');
    disp('********** processed .bin file saved ************');
    disp('*************************************************');
    
%% plot %%

    

    figure
    plot(phase_diff, tmpk_fringe(:, 1),  '-o', 'MarkerSize',5, 'MarkerFaceColor','g', 'color', 'g');
    hold on
    plot(equal_space_k, y_bg(:, 1),  '-o', 'MarkerSize',5, 'MarkerFaceColor','b', 'color', 'b');
    hold off
    legend("resampled data (MATLAB)", "original raw data", "location", "southeast");



    figure
    plot(phase_diff, float_data, '-o', 'MarkerSize',5, 'MarkerFaceColor','r', 'color', 'r', 'LineWidth', 1.5);
    hold on
    plot(phase_diff, tmpk_fringe(:, 1),  '-x', 'MarkerSize',7, 'MarkerFaceColor','g', 'color', 'g', 'LineWidth', 1);
    hold off
    legend("resampled data (designed hardware)", "resampled data (MATLAB)", "location", "southeast");



    
%% other process for "Processeddata" %%

    log_p = log(abs(Processeddata(:,:,1))); %% p stands for "Processeddata"
    [min1_log_p, ind1] = min(log_p);
    [min2_log_p, ind2] = min(min1_log_p);
    noise = mean(mean(log_p(end/2:end, :)));
    denoise_p = abs(log_p-noise);
    rescale_p = denoise_p./ max(max(denoise_p)) * 65535;

%% psnr, ssim %%
    psnr_vp = psnr(uint16(rescale_p), uint16(rescale_vdata));
    ssim_vp = ssim(uint16(rescale_p), uint16(rescale_vdata));

%% plot %%
    for cnt=1:20
        figure; imagesc(log10(abs(Processeddata(:,:,cnt  ))));colormap gray;
        figure; imagesc(rescale_p(:, :, cnt));colormap gray;
        % waitforbuttonpress;
    end 

    

end